### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by circlebeats** [hunter-isaiah96/vue-wave-sufver#2]
On: https://vuejsexamples.com/vue-wrapper-for-wavesurfer-js/

you've set the install to vue-wavesurfer. The correct is vue-wave-surfer.

**Comment by hunter-isaiah96** [comment]
Hey @circlebeats , that is documentation from a previous version, I also did not post that example.

**Comment by circlebeats** [comment]
my apologies
